### ISSUE TITLE
I get an error when I enter the project name in GITLAB_PROJECT_NAME 

### ISSUE THREAD

**Issue by nilfs** [sue445/gitlab_mr_release#50]
It may have been used incorrectly, but it didn't work so please let me know. 

When I create .env.gitlab and execute the command, the following error is output. However, if I enter the project ID instead of the project name in GITLAB_PROJECT_NAME, I get the expected result. 

.env.gitlab
```
GITLAB_API_ENDPOINT=https://gitlab.com/api/v4/
GITLAB_API_PRIVATE_TOKEN=XXXXXXXXXXX
GITLAB_PROJECT_NAME=gitlab-org/gitlab-foss
TEMPLATE_FILE=gitlab_mr_release.md.erb
DEFAULT_TITLE=Release <%= Time.now %> <%= source_branch %> -> <%= target_branch %>
DEFAULT_SOURCE_BRANCH=master
DEFAULT_TARGET_BRANCH=develop
#DEFAULT_LABELS=release
```

result of 'gitlab_mr_release create'
```
Traceback (most recent call last):
        13: from /usr/local/bin/gitlab_mr_release:23:in `<main>'
        12: from /usr/local/bin/gitlab_mr_release:23:in `load'
        11: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/exe/gitlab_mr_release:4:in `<top (required)>'
        10: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
         9: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
         8: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         7: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         6: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/lib/gitlab_mr_release/cli.rb:55:in `create'
         5: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/lib/gitlab_mr_release/project.rb:44:in `create_merge_request'
         4: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/lib/gitlab_mr_release/project.rb:31:in `merge_request_iids_between'
         3: from /var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab.rb:28:in `method_missing'
         2: from /var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/client/repositories.rb:59:in `compare'
         1: from /var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class:Request>'
/var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:59:in `validate': Server responded with code 404, message: 404 Ref Not Found. Request URI: https://gitlab.com:443https://gitlab.com/api/v4/projects/gitlab-org%2Fgitlab-foss/repository/compare?from=develop&to=master (Gitlab::Error::NotFound)
```

## System configuration
- ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- gitlab (4.17.0)

**Comment by sue445** [comment]
> Server responded with code 404, message: 404 Ref Not Found. Request URI: https://gitlab.com:443https://gitlab.com/api/v4/projects/gitlab-org%2Fgitlab-foss/repository/compare?from=develop&to=master (Gitlab::Error::NotFound)

Because there isn't `develop` branch on https://gitlab.com/gitlab-org/gitlab-foss

https://gitlab.com/gitlab-org/gitlab-foss/-/tree/develop

![image](https://user-images.githubusercontent.com/608755/107226186-2595a900-6a5d-11eb-8d7e-3778ce7d11a2.png)

This error is the correct behavior of GitLab

>  if I enter the project ID instead of the project name in GITLAB_PROJECT_NAME, I get the expected result.

What number did you enter for the project ID?

I got the same result as for `gitlab-org/gitlab-foss`

```ruby
irb(main):018:0> Gitlab.repo_compare("gitlab-org/gitlab-foss", "develop", "master").commits
Traceback (most recent call last):
        8: from /Users/sue445/.rbenv/versions/3.0.0/bin/irb:23:in `<main>'
        7: from /Users/sue445/.rbenv/versions/3.0.0/bin/irb:23:in `load'
        6: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        5: from (irb):16:in `<main>'
        4: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab.rb:28:in `method_missing'
        3: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab/client/repositories.rb:59:in `compare'
        2: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class:Request>'
        1: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:59:in `validate'
Gitlab::Error::NotFound (Server responded with code 404, message: 404 Ref Not Found. Request URI: https://gitlab.com:443https://gitlab.com/api/v4/projects/gitlab-org%2Fgitlab-foss/repository/compare?from=develop&to=master)

irb(main):022:0* Gitlab.project("gitlab-org/gitlab-foss").id
=> 13083

irb(main):023:0> Gitlab.repo_compare(13083, "develop", "master").commits
Traceback (most recent call last):
        8: from /Users/sue445/.rbenv/versions/3.0.0/bin/irb:23:in `<main>'
        7: from /Users/sue445/.rbenv/versions/3.0.0/bin/irb:23:in `load'
        6: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        5: from (irb):23:in `<main>'
        4: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab.rb:28:in `method_missing'
        3: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab/client/repositories.rb:59:in `compare'
        2: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class:Request>'
        1: from /Users/sue445/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:59:in `validate'
Gitlab::Error::NotFound (Server responded with code 404, message: 404 Ref Not Found. Request URI: https://gitlab.com:443https://gitlab.com/api/v4/projects/13083/repository/compare?from=develop&to=master)
```

**Comment by nilfs** [comment]
I'm sorry. While trying various parameters, I pasted the .env.gitlab I was working on.

I created a simple sample repository and tried to reproduce it.

Create the following .env.gitlab and execute "gitlab_mr_release create"
`` ```
GITLAB_API_ENDPOINT = https://gitlab.com/api/v4/
GITLAB_API_PRIVATE_TOKEN = "XXXXXXXXXXXX"
GITLAB_PROJECT_NAME = nilfs_group / mr_test_group / mr_test /
TEMPLATE_FILE = gitlab_mr_release.md.erb
DEFAULT_TITLE = Draft: <% = Time.now%> <% = source_branch%>-> <% = target_branch%>
DEFAULT_SOURCE_BRANCH = develop
DEFAULT_TARGET_BRANCH = master
#DEFAULT_LABELS = release
`` ```

Such a log is output and it fails.
`` ```
/ projects / nilfs_group% 2Fmr_test_group% 2Fmr_test% 2F / repository / compare
Traceback (most recent call last):
        13: from / usr / local / bin / gitlab_mr_release: 23: in `<main>'
        12: from / usr / local / bin / gitlab_mr_release: 23: in `load'
        11: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/exe/gitlab_mr_release: 4: in `<top (required)>'
        10: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485: in `start'
         9: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb: 392: in `dispatch'
         8: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         7: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         6: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/lib/gitlab_mr_release/cli.rb:55:in `create'
         5: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/lib/gitlab_mr_release/project.rb:44:in `create_merge_request'
         4: from /var/lib/gems/2.7.0/gems/gitlab_mr_release-1.1.1/lib/gitlab_mr_release/project.rb:31:in `merge_request_iids_between'
         3: from /var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab.rb:28:in `method_missing'
         2: from /var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/client/repositories.rb:60:in `compare'
         1: from /var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class: Request>'
/var/lib/gems/2.7.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:59:in `validate': Server responded with code 404, message: 404 Project Not Found. Request URI: https://gitlab.com:443 https://gitlab.com/api/v4/projects/nilfs_group%2Fmr_test_group%2Fmr_test%2F/repository/compare?from=master&to=develop (Gitlab :: Error :: NotFound)
`` ```

Instead, create an .env.gitlab like the one below and run "gitlab_mr_release create" and it will succeed.
`` ```
GITLAB_API_ENDPOINT = https://gitlab.com/api/v4/
GITLAB_API_PRIVATE_TOKEN = "XXXXXXXXXXXXXX"
GITLAB_PROJECT_NAME = 24288216
TEMPLATE_FILE = gitlab_mr_release.md.erb
DEFAULT_TITLE = Draft: <% = Time.now%> <% = source_branch%>-> <% = target_branch%>
DEFAULT_SOURCE_BRANCH = develop
DEFAULT_TARGET_BRANCH = master
#DEFAULT_LABELS = release
`` ```

The cause was that there was an extra / in the project name when copying the project and group name from the URL.

I apologize to you for a fuss over. The command worked successfully.

Thanks for creating this tool.
